### ISSUE TITLE
Possible to take multiple screenshots?

### ISSUE THREAD

**Issue by stephenplusplus** [callmehiphop/video-screen#4]
Is it possible to support:

multiple screens, e.g. at 0:01 and 1:34?

a range, e.g. 0:01 - 0:10?

**Comment by callmehiphop** [comment]
It is, but I think that would require a change to the API ;~;

**Comment by stephenplusplus** [comment]
Your API? No big deal, you're still on [0.0.0](https://github.com/callmehiphop/video-screen/blob/7ad25953e0b49a2f17e0605e9d342b0d2f6e8990/package.json#L3) :P
